// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Creates a sale, its line items, stock movements and an optional initial payment
 * in a single transaction. Totals are recomputed server-side (the client cannot
 * tamper with them) and stock availability is validated before anything is written.
 */
async createSale(input: CreateSaleInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sale", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a payment against a sale and re-syncs its balance/status atomically.
 */
async recordPayment(saleId: number, amount: number, method: string | null, note: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_payment", { saleId, amount, method, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a payment and re-syncs the sale's balance/status atomically.
 */
async deletePayment(paymentId: number, saleId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_payment", { paymentId, saleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Voids a sale: a fiscally-issued invoice is never deleted (that would break the
 * gap-free TVA sequence). Instead it is marked `status = 'void'` — the row and its
 * invoice number are retained for audit — while stock is restored, any insurer claim
 * is cancelled, and the patient owes nothing. Rejected if the sale already has a
 * credit note (process/undo the return first) or is already void. Recorded payments
 * are left in place as a historical record; refunding them is a separate cash action.
 */
async voidSale(saleId: number, reason: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("void_sale", { saleId, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Processes a return as a numbered credit note (avoir): validates returnable quantities,
 * restocks the goods, and credits the customer the **net amount actually borne** for the
 * returned lines — i.e. their share after the global discount and insurer coverage
 * (`line_total × (total − covered) / subtotal`), not the raw line price. A 'refund' is
 * capped at what the customer has paid (use 'balance' for the unpaid portion); a 'balance'
 * credit reduces the sale's outstanding balance via sync_sale_balance. The original
 * invoice is left intact. Insurer-claim reconciliation for returned goods is handled
 * separately on the claims screen. Returns the new credit-note id.
 */
async createReturn(input: CreateReturnInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_return", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an insurance claim's status. The 'rejected' path re-bills the patient: the
 * previously-covered amount is zeroed and the sale's balance re-synced, so a rejected
 * claim no longer silently disappears from what the patient owes (audit finding E1).
 */
async setClaimStatus(claimId: number, status: string, claimRef: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_claim_status", { claimId, status, claimRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merges a duplicate patient into a surviving one: re-points all of the duplicate's
 * records (sales, prescriptions, jobs, appointments, credit notes, activity, held
 * carts, custom fields) onto `keep_id`, then deletes the now-empty duplicate. Custom
 * fields that would collide (same attribute on both) keep the survivor's value.
 */
async mergePatients(keepId: number, dupId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_patients", { keepId, dupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordStockChange(input: StockChangeInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_stock_change", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Moves a job to a new pipeline stage, stamps delivered_at at 'delivered'
 * (clearing it on a backward move), and records the stage change in job_events
 * (per-stage history, H1) — atomically. Replaces the frontend transaction in
 * `src/db/jobs.ts`.
 */
async updateJobStatus(jobId: number, status: string, note: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_job_status", { jobId, status, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merges colour `from_id` into `into_id`: re-points every product/variant FK and
 * the denormalized variant colour mirror, moves aliases, then archives the
 * source — atomically (a half-merged colour is the bad state). Replaces the
 * frontend transaction in `src/db/colors.ts`.
 */
async mergeColor(fromId: number, intoId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_color", { fromId, intoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records an operating expense (rent, salaries, utilities, ...). Stock bought
 * from suppliers is *not* an expense here — it reaches the P&L as cost of goods
 * when the stock sells.
 */
async createExpense(input: ExpenseInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_expense", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edits a recorded expense.
 */
async updateExpense(id: number, input: ExpenseInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_expense", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes a recorded expense.
 */
async deleteExpense(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_expense", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a consistent snapshot of the live database to `dest_path` (a full path
 * with filename chosen by the frontend) via `VACUUM INTO` — SQLite's online
 * backup: correct even while other connections keep writing (no file copy of a
 * moving target), and the output is compacted. Returns the path.
 */
async backupDatabase(destPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_database", { destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restores the database from `src_path`. First copies the current DB to
 * `safety_path` (so a bad restore is reversible), then overwrites the live file and
 * removes the WAL/SHM sidecars so the restored file is authoritative. The frontend
 * relaunches the app afterwards so the new database is reopened cleanly.
 */
async restoreDatabase(srcPath: string, safetyPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_database", { srcPath, safetyPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes UTF-8 `content` to `dest_path`. Used for CSV exports (the frontend builds
 * the CSV and picks the destination); a Rust command avoids the plugin-fs scope
 * restrictions for arbitrary user-chosen paths.
 */
async exportTextFile(destPath: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_text_file", { destPath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends an ESC/POS receipt to `target` — a printer device path (e.g. /dev/usb/lp0)
 * or a raw print queue/file. Connection specifics are environment-dependent and
 * must be configured (and tested) against the actual hardware.
 */
async printReceipt(target: string, lines: ReceiptLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("print_receipt", { target, lines }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prints a barcode label to the configured thermal/label printer (`receipt_target`).
 */
async printLabel(input: LabelInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("print_label", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CreateReturnInput = { sale_id: number; 
/**
 * 'refund' = cash back to the customer; 'balance' = credit the sale's outstanding balance.
 */
method: string; notes: string | null; items: ReturnItemInput[] }
export type CreateSaleInput = { 
/**
 * `None` for a walk-in / quick sale with no registered customer.
 */
patient_id: number | null; prescription_id: number | null; sale_date: string; discount_type: string; discount_value: number; notes: string | null; items: SaleItemInput[]; initial_payment: number | null; payment_method: string | null; payer_id: number | null; coverage_pct: number | null }
export type ExpenseInput = { 
/**
 * Local calendar day, `YYYY-MM-DD`.
 */
expense_date: string; category: string; 
/**
 * Centimes; must not be negative.
 */
amount: number; note: string | null; supplier_id: number | null; method: string | null }
/**
 * A barcode label to print on the thermal/label printer.
 */
export type LabelInput = { value: string; format: string; name: string; price: string; sku: string }
/**
 * One line of a thermal receipt. The frontend pre-formats the text (column padding,
 * width) and chooses per-line alignment/emphasis; Rust turns it into ESC/POS bytes.
 */
export type ReceiptLine = { text: string; align: string; bold: boolean; big: boolean }
export type ReturnItemInput = { sale_item_id: number; quantity: number }
export type SaleItemInput = { product_id: number | null; 
/**
 * When set, stock is tracked on this product variant instead of the product.
 */
variant_id: number | null; description: string; unit_price: number; quantity: number; item_discount: number }
/**
 * Atomic stock change (delivery or adjustment) for a product or a variant.
 * Replaces the frontend BEGIN/COMMIT transactions in `src/db/stock.ts`, which
 * were unsafe on the shared pool (each statement lands on an arbitrary pooled
 * connection). The invariant: on-hand quantity never diverges from the
 * movement ledger, and a supplier debt is only booked with its delivery.
 */
export type StockChangeInput = { product_id: number | null; 
/**
 * When set, stock is tracked on this product variant instead of the product.
 */
variant_id: number | null; 
/**
 * "delivery" or "adjustment" — recorded verbatim in stock_movements.type.
 */
movement_type: string; quantity_change: number; 
/**
 * When set, becomes the product/variant's new purchase price (centimes).
 */
purchase_price: number | null; note: string | null; supplier_id: number | null; 
/**
 * Total purchase cost (centimes) to book as a supplier debt.
 */
debt_amount: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
