// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Creates a sale, its line items, stock movements and an optional initial payment
 * in a single transaction. Totals are recomputed server-side (the client cannot
 * tamper with them) and stock availability is validated before anything is written.
 */
async createSale(input: CreateSaleInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sale", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a payment against a sale and re-syncs its balance/status atomically.
 */
async recordPayment(saleId: number, amount: number, method: string | null, note: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_payment", { saleId, amount, method, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a payment and re-syncs the sale's balance/status atomically.
 */
async deletePayment(paymentId: number, saleId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_payment", { paymentId, saleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restores stock for a sale's items (logging adjustment movements) and deletes the
 * sale (cascading items/payments) in a single transaction.
 */
async deleteSale(saleId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_sale", { saleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Processes a return as a credit note: validates returnable quantities (against what
 * was sold minus already-returned), restocks the goods, and records the credit note
 * and its items as a cash refund. The original sale is left intact. Returns the new
 * credit-note id.
 */
async createReturn(input: CreateReturnInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_return", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checkpoints the WAL so the `.db` file is self-contained, then copies it to
 * `dest_path` (a full path with filename chosen by the frontend). Returns the path.
 */
async backupDatabase(destPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_database", { destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restores the database from `src_path`. First copies the current DB to
 * `safety_path` (so a bad restore is reversible), then overwrites the live file and
 * removes the WAL/SHM sidecars so the restored file is authoritative. The frontend
 * relaunches the app afterwards so the new database is reopened cleanly.
 */
async restoreDatabase(srcPath: string, safetyPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_database", { srcPath, safetyPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes UTF-8 `content` to `dest_path`. Used for CSV exports (the frontend builds
 * the CSV and picks the destination); a Rust command avoids the plugin-fs scope
 * restrictions for arbitrary user-chosen paths.
 */
async exportTextFile(destPath: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_text_file", { destPath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends an ESC/POS receipt to `target` — a printer device path (e.g. /dev/usb/lp0)
 * or a raw print queue/file. Connection specifics are environment-dependent and
 * must be configured (and tested) against the actual hardware.
 */
async printReceipt(target: string, lines: ReceiptLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("print_receipt", { target, lines }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prints a barcode label to the configured thermal/label printer (`receipt_target`).
 */
async printLabel(input: LabelInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("print_label", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CreateReturnInput = { sale_id: number; method: string; notes: string | null; items: ReturnItemInput[] }
export type CreateSaleInput = { patient_id: number; prescription_id: number | null; sale_date: string; discount_type: string; discount_value: number; notes: string | null; items: SaleItemInput[]; initial_payment: number | null; payment_method: string | null; payer_id: number | null; coverage_pct: number | null }
/**
 * A barcode label to print on the thermal/label printer.
 */
export type LabelInput = { value: string; format: string; name: string; price: string; sku: string }
/**
 * One line of a thermal receipt. The frontend pre-formats the text (column padding,
 * width) and chooses per-line alignment/emphasis; Rust turns it into ESC/POS bytes.
 */
export type ReceiptLine = { text: string; align: string; bold: boolean; big: boolean }
export type ReturnItemInput = { sale_item_id: number; quantity: number }
export type SaleItemInput = { product_id: number | null; 
/**
 * When set, stock is tracked on this product variant instead of the product.
 */
variant_id: number | null; description: string; unit_price: number; quantity: number; item_discount: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
